### ISSUE TITLE
Wallet shows 0 XLM balance in local Standalone/Futurenet from quickstart

### ISSUE THREAD

**Issue by esteblock** [stellar/freighter#1009]
### What version are you using?
Freighter Wallet: 5.6.4
### What did you do?
1.- Run a quickstart standalone node in port 8000 with (preview 11)

```bash
quickstartHash="testing@sha256:263ab2e416e72b068ea84e4db09971a733b885121225518004520f27f8effa61"
ARGS="--standalone"
docker run --rm -ti \
  --name stellar \
  -p 8000:8000 \
  stellar/quickstart:${quickstartHash} \
  $ARGS \
  --enable-soroban-rpc \
  --protocol-version 20 \
  "$@" 
```

2.- Configure Standalone network in Freighter

   |   |   |
   |---|---|
   | Name | Local Standalone |
   | HORIZON RPC URL | http://localhost:8000/soroban/rpc |
   | SOROBAN RPC URL | http://localhost:8000/soroban/rpc |
   | Passphrase | Standalone Network ; February 2017 |
   | Allow HTTP connection | Enabled |
   | Switch to this network | Enabled |
   
2.- Fund my wallet with Friendbot:
`http://localhost:8000/friendbot?addr=<your address>`

### What did you expect to see?
My balance: 10,000 XLM
I check usign js script that my wallet has been correclty funded.

### What did you see instead?
I see that my balance is 0

# Comment: 
This also happens with local Futurenet.
But if I go to the provided Future Net config (https://horizon-futurenet.stellar.org), the balance appears correctly

**Comment by aristidesstaffieri** [comment]
I believe this is happening because the config shows `HORIZON RPC URL=http://localhost:8000/soroban/rpc` when it should be `HORIZON RPC URL=http://localhost:8000`. I just tried this out and was able to see my balance, here is my full config -
![Screenshot 2023-10-18 at 9 45 48 AM](https://github.com/stellar/freighter/assets/6886006/0ec98fa2-fd39-454b-9fc5-ba49a6acf613)
