### ISSUE TITLE
[spike] explore how to display USD value of account balances

### ISSUE THREAD

**Issue by JakeUrban** [stellar/freighter#1593]
relates to #274

**Comment by aristidesstaffieri** [comment]
### Options
One way that we can get a USD value for some assets is by using our existing StellarExpert integration to query their assets list which provides a 7 day average price of the asset in USD. They source their exchange rates by observing buy/sell data on the sdex.

Another way would be to use the Reflector protocol to subscribe to price feeds for different assets.

Other options include building our own oracle protocol or indexer, but since they are very similar to the previous two options, I'll list pros and cons for the existing options only.

### Pros & Cons
StellarExpert
**Pro**
This API exists today and the work is done as far as the integration is concerned. This is likely the least effort route.

**Con**
We would rely on StellarExpert and their implementation for a very sensitive piece of data in Freighter. 
How do we know if the data is correct? 
How do we deal with downtime or un-availability?
Is it acceptable to only provide USD values for assets that have a market on the sdex(no custom tokens)?

Reflector
**Pro**
An open and auditable protocol for feed data.
Protected by multi-sig
Flexibility in regards to ingestion(we write the consuming contract)

**Con**
More integration work - we would need to write the contracts that interact with the Oracles and consider how our client contract will work.
Protocols need to integrate with Reflector to be represented. Blend and Slender are integrated today but future protocols will have to do the same before we can access their token price feeds. How do we discover new Oracles?
Likely will result in slower API response times due to the architecture differences(integrating with a contract vs a DB backed API)

**Comment by JakeUrban** [comment]
> Is it acceptable to only provide USD values for assets that have a market on the sdex(no custom tokens)?

I think this makes the stellar.expert route ineligible, but we can ask stellar.expert if they're planning to incorporate soroban protocols for pricing custom tokens in the near future.

> we would need to write the contracts that interact with the Oracles and consider how our client contract will work.

Does the oracle contract itself not expose an interface that can be called by off-chain clients? Why does it have to be consumed by another contract?

They also seem to have a [subscriptions service](https://reflector.network/subscription), which may make our lives easier.

**Comment by aristidesstaffieri** [comment]
> I think this makes the stellar.expert route ineligible, but we can ask stellar.expert if they're planning to incorporate soroban protocols for pricing custom tokens in the near future.

Sounds good, I can start a convo with Orbit

> Does the oracle contract itself not expose an interface that can be called by off-chain clients? Why does it have to be consumed by another contract?

The docs don't explicitly state this but looking at the examples it seems like the price oracle publishes data on chain and the expected consumer flow is to have a contract that interfaces with the `PriceOracleClient`. So as far as I can tell, the Reflector nodes publish data to the oracle the oracle has a client that they expect other contracts to use. I do see what you're asking though, how come we can't just fetch the underlying data entry that the oracle writes to using some off chain workflow. I can't think of a reason right away so maybe this is possible. I'll bring this up in the Reflector discord server to get a more clear answer about it.

> They also seem to have a [subscriptions service](https://reflector.network/subscription), which may make our lives easier.
It seems like the added benefit is that you get a webhook that can tell you when the oracle has updated data but the webhook does not return the data, you still need to get it from the ledger. I think it does make our lives easier but also wonder why the webhook can't return the actual data which would really simplify things for clients.

**Comment by JakeUrban** [comment]
> [stellar.expert] provides a 7 day average price of the asset in USD

I looked at their [docs](https://stellar.expert/openapi.html#tag/Asset-Info-API/operation/getAllAssets) and didn't see this. I only saw a 7-day volume metric. I'm also not sure we'd want a 7-day average. Ideally this is closer to real time.

I also realized that reflector provides prices for a fairly limited set of onchain assets.

Honestly I'm not sure either of these solutions are the right fit. I think our ideal solution would be an API that exposes real-time prices for all onchain assets that are at or greater than a specific daily/weekly trading volume in USD terms. These prices would likely need to be aggregated from the most popular liquidity sources on Stellar (SDEX + Soroswap + Aquarius + etc.).

I would expect this type of product to be built by someone in the ecosystem once there was a sufficient level of trading activity / liquidity onchain, and maybe we're just not there yet.

**Comment by aristidesstaffieri** [comment]
> I looked at their [docs](https://stellar.expert/openapi.html#tag/Asset-Info-API/operation/getAllAssets) and didn't see this. I only saw a 7-day volume metric. I'm also not sure we'd want a 7-day average. Ideally this is closer to real time.

I think the docs are missing this piece but I looked at the API that provides the data for the "assets on the ledger" section of this page https://stellar.expert/explorer/public
It hits the API route that you linked but also includes a key for `price7d` which I don't see in the doc, those values correspond with what I see in the UI for the asset price delta in USD.


> Honestly I'm not sure either of these solutions are the right fit. I think our ideal solution would be an API that exposes real-time prices for all onchain assets that are at or greater than a specific daily/weekly trading volume in USD terms. These prices would likely need to be aggregated from the most popular liquidity sources on Stellar (SDEX + Soroswap + Aquarius + etc.).

I would expect this type of product to be built by someone in the ecosystem once there was a sufficient level of trading activity / liquidity onchain, and maybe we're just not there yet.

Yeah I don't think this exists, but it could be built on top of Reflector. This might be a good bounty type of thing to introduce to the community if we think that this should be built externally.
