### ISSUE TITLE
Feature Request: Make it easier to merge Freighter into another wallet

### ISSUE THREAD

**Issue by the-solipsist** [stellar/freighter#180]
### What problem does your feature solve?

If someone wishes to close their Freighter wallet, and shift to another wallet, there is no way to do so since the secret key of the source account (the Freighter wallet) is not available to users.

### What would you like to see?

Be able to merge the Freighter wallet with another wallet.

### What alternatives are there?

Provide a way to gain access to the seed / secret key (with sufficient hurdles to prevent most users from doing so), as that will allow for merge operation to be conducted through the Stellar Laboratory's tools.

**Comment by vcarl** [comment]
I'm not sure I'm understanding, a quick test (without submitting, because I don't actually want to merge my Freighter account) seems to show that the transaction builder is able to create a "merge account" transaction using the public key from Freighter and signing it via the Freighter UI. That seems like it meets the need here, unless I'm misunderstanding what you're asking for?

**Comment by the-solipsist** [comment]
My apologies. No, you didn't misunderstand me.  I had just missed the "sign with Freighter" option.  I'm closing this issue.  

Once again, sorry for this!
