### ISSUE TITLE
Public key is different with Albedo

### ISSUE THREAD

**Issue by ralphilius** [stellar/freighter#256]
### What did you do?

 - Create an account with albedo.link
 - Save seed phase
 - Open Freighter and import account
 - Paste the seed phase

### What did you expect to see?
Same public address for both services

### What did you see instead?
Different public addresses

**Comment by piyalbasu** [comment]
Hi, thanks for surfacing this. I looked into it, and the issue is that one mnemonic phrase can be linked to many keypairs. Albedo and Freighter just happen  to be generating different keypairs from the same phrase. Freighter defaults to getting account `0` from the phrase while Albedo uses a different methodology. This is the package that Freighter uses to do this: https://github.com/chatch/stellar-hd-wallet

A workaround for this issue is to import your Albedo account by secret key. Hope that helps.
