### ISSUE TITLE
Remove side effects from getPublicKey

### ISSUE THREAD

**Issue by chadoh** [stellar/freighter#830]
### What problem does your feature solve?

I want to follow common usability/accessibility guidelines and not open pop-ups without explicit user action, but Freighter makes this hard. For example, most apps will want to check if Freighter is 1. installed, and 2. if a user has enabled it for this site and if not, 3. prompt the user to enable it.

Freighter merges 2 & 3 into one `getPublicKey` function, which automatically opens a pop-up if the user hasn't yet enabled it (or re-prompts, if it's been a while).

### What would you like to see?

I would like to see `getPublicKey` split into two, maybe three new functions:

- `isEnabled`: does not have side effects, does not prompt the user, just returns `true` if the user has already enabled Freighter for this site, `false` otherwise
- `enable`: prompt the user to enable this page to use to Freighter

Additionally, I think `getPublicKey` should return `undefined` if the user hasn't enabled Freighter yet rather than prompting them to enable Freighter. But since that makes for a confusing upgrade path for developers, I'd rather see a new function added with the no-side-effect version of `getPublicKey`. Naming is tough for this one. Maybe:

- `getUser`, which returns an object that includes `publicKey`?

Then `getPublicKey` can be marked as deprecated, and removed in the next major release.

### What alternatives are there?

I'm open to whatever function names y'all think are best.

For now, the workaround is to keep opening pop-ups on page load, or just don't load sections of the app that require the user's address until they click something, or to have apps manage this sort of information in localStorage, rather than moving this sort of common behavior to Freighter.

**Comment by chadoh** [comment]
Maybe `isConnected` could also be renamed to `isInstalled`, and `isConnected` can be removed from the same major version that removes `getPublicKey`?

**Comment by piyalbasu** [comment]
This has been completed by #861 

I'm holding off on deprecating `getPublicKey` because I think the flow of an app trying to get a user's public key, and then the user having to either grant access OR authenticate (enter their pw) and then grant access is pretty common. This flow "solves" a lot of problems that might prevent the app from getting user info and ultimately ends with the app getting the info it requested. `getUserInfo` can fail because of lack of authentication and/or because of lack of being allowed. If it does fail, the app won't know why or how to fix it. It then becomes up to the user to figure out what the problem is. 

I'm comfortable with having one flow that prompts the user and one that doesn't. The app can decide what it wants to do

I'll look at renaming `isConnected` to `isInstalled` in a later version
