### ISSUE TITLE
The words on password popup are confusing 

### ISSUE THREAD

**Issue by GHesericsu** [stellar/freighter#923]
### What version are you using?

5.2.5

### What did you do?

I tried to submit a transaction and freighter asked me for password

### What did you expect to see?
A popup that asked me for password with clear instruction is asking for password

### What did you see instead?

Do you want my password or want an address? :) 
![Screen Shot 2023-08-01 at 6 20 04 PM](https://github.com/stellar/freighter/assets/60202455/b6d1cf75-5bc5-452b-bdb6-ff7d495ee1df)

**Comment by CassioMG** [comment]
This seems like a UX issue. Whenever a user tries to create a new stellar address this screen on the right is displayed:
![Image](https://github.com/user-attachments/assets/f8d7c3dc-8259-4480-a740-b19aa6d284a9)
It could sound a bit confusing as users _could_ interpret the "Add" as a command to input an existing stellar address to the input field which actually has "Enter Password" as the placeholder.

I'd like to propose we change the copy a little bit on this screen so it's consistent with the button on the left which has "Create a new Stellar address" as the title, instead of using the "Add" verb.
So the second screen would look like this:
- Title: "Enter password to create a new Stellar address"
- Placeholder: "Enter Password"
- CTA: "Create New Address"
![Image](https://github.com/user-attachments/assets/d268a5a6-a3e0-47df-a01d-b78e450eb713)

@GHesericsu @sdfcharles @piyalbasu @aristidesstaffieri @JakeUrban curious about your thoughts here

**Comment by JakeUrban** [comment]
Is there a reason why we require the user's password to create an address?

Regardless, I would probably vote for a less verbose prompt. So instead of "Create a new Stellar address" --> "Enter Password to create a new Stellar address" --> "Create New Address", I would vote for "Create a new Stellar address" --> "Enter Password" --> "Create New Address".

**Comment by aristidesstaffieri** [comment]
> This seems like a UX issue. Whenever a user tries to create a new stellar address this screen on the right is displayed: ![Image](https://github.com/user-attachments/assets/f8d7c3dc-8259-4480-a740-b19aa6d284a9) It could sound a bit confusing as users _could_ interpret the "Add" as a command to input an existing stellar address to the input field which actually has "Enter Password" as the placeholder.
> 
> I'd like to propose we change the copy a little bit on this screen so it's consistent with the button on the left which has "Create a new Stellar address" as the title, instead of using the "Add" verb. So the second screen would look like this:
> 
> * Title: "Enter password to create a new Stellar address"
> * Placeholder: "Enter Password"
> * CTA: "Create New Address"
>   ![Image](https://github.com/user-attachments/assets/d268a5a6-a3e0-47df-a01d-b78e450eb713)
> 
> [@GHesericsu](https://github.com/GHesericsu) [@sdfcharles](https://github.com/sdfcharles) [@piyalbasu](https://github.com/piyalbasu) [@aristidesstaffieri](https://github.com/aristidesstaffieri) [@JakeUrban](https://github.com/JakeUrban) curious about your thoughts here

I agree that the change proposed is more clear, it would be nice if it all fit on one line but I think the copy is more clear in your patch.

**Comment by aristidesstaffieri** [comment]
> Is there a reason why we require the user's password to create an address?
> 
> Regardless, I would probably vote for a less verbose prompt. So instead of "Create a new Stellar address" --> "Enter Password to create a new Stellar address" --> "Create New Address", I would vote for "Create a new Stellar address" --> "Enter Password" --> "Create New Address".

This is an artifact of how the account/key management is implemented as should be addressable with the work @piyalbasu is doing to remove this constraint due to the same annoyance in other flows(change account, send, and manage assets).

**Comment by aristidesstaffieri** [comment]
> > Is there a reason why we require the user's password to create an address?
> > Regardless, I would probably vote for a less verbose prompt. So instead of "Create a new Stellar address" --> "Enter Password to create a new Stellar address" --> "Create New Address", I would vote for "Create a new Stellar address" --> "Enter Password" --> "Create New Address".
> 
> This is an artifact of how the account/key management is implemented as should be addressable with the work [@piyalbasu](https://github.com/piyalbasu) is doing to remove this constraint due to the same annoyance in other flows(change account, send, and manage assets).

Sorry scratch that, in this case it looks to be implemented specifically to check password in this step but I don't think there is a technical reason to do it.

**Comment by JakeUrban** [comment]
> Sorry scratch that, in this case it looks to be implemented specifically to check password in this step but I don't think there is a technical reason to do it.

Objections against removing it? @sdfcharles?

**Comment by CassioMG** [comment]
Implemented here: https://github.com/stellar/freighter/pull/1645

**Comment by piyalbasu** [comment]
I like this solution of not even asking for the password! I think something we'll need to consider is what happens when the user's session times out after 24 hours, because we clear the user's password and private key in that scenario. We'll need the user to reauth in that case because the password is necessary for storing the new keypair in KeyManager: https://github.com/stellar/freighter/blob/master/extension/src/background/messageListener/popupMessageListener.ts#L282

Maybe the UX should be something like:
* if we have the password, just add the address and automatically redirect them to the Account view for the new address
* if we don't have the password, we can use the old UX of asking for the user's password (with more clear copy, as was originally intended by this ticket)

**Comment by CassioMG** [comment]
> I like this solution of not even asking for the password! I think something we'll need to consider is what happens when the user's session times out after 24 hours, because we clear the user's password and private key in that scenario. We'll need the user to reauth in that case because the password is necessary for storing the new keypair in KeyManager: https://github.com/stellar/freighter/blob/master/extension/src/background/messageListener/popupMessageListener.ts#L282
> 
> Maybe the UX should be something like:
> 
> * if we have the password, just add the address and automatically redirect them to the Account view for the new address
> * if we don't have the password, we can use the old UX of asking for the user's password (with more clear copy, as was originally intended by this ticket)

@piyalbasu that makes a lot of sense, I'll make the changes so that it asks the password in case it is not stored. Thanks for the review!

**Comment by CassioMG** [comment]
Implemented with new changes on this other PR: https://github.com/stellar/freighter/pull/1682
